services:
  - type: web
    name: Backend-Tarea-Dario-
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        value: "postgresql://dario_backend_database_user:S2siW9Y20hrthNOZsuyoWR9VJacyu85I@dpg-cv68kofnoe9s73bsqin0-a/dario_backend_database"
